#ifndef LOLBISON_AST_H_
#define LOLBISON_AST_H_


#include "expressions/binary_ops/BinaryAnd.h"
#include "expressions/binary_ops/BinaryDiv.h"
#include "expressions/binary_ops/BinaryEq.h"
#include "expressions/binary_ops/BinaryMax.h"
#include "expressions/binary_ops/BinaryMin.h"
#include "expressions/binary_ops/BinaryMod.h"
#include "expressions/binary_ops/BinaryMul.h"
#include "expressions/binary_ops/BinaryNeq.h"
#include "expressions/binary_ops/BinaryOp.h"
#include "expressions/binary_ops/BinaryOr.h"
#include "expressions/binary_ops/BinarySub.h"
#include "expressions/binary_ops/BinarySum.h"
#include "expressions/binary_ops/BinaryXor.h"
#include "expressions/ArrayAccess.h"
#include "expressions/BooleanLiteral.h"
#include "expressions/Identifier.h"
#include "expressions/It.h"
#include "expressions/Join.h"
#include "expressions/LogicalNot.h"
#include "expressions/NumberLiteral.h"
#include "expressions/StringLiteral.h"
#include "statements/ArrayAssign.h"
#include "statements/ArrayDecl.h"
#include "statements/ArrayNewIndex.h"
#include "statements/Break.h"
#include "statements/ExprStatement.h"
#include "statements/Print.h"
#include "statements/VarAssign.h"
#include "statements/VarDecl.h"
#include "Program.h"
#include "AstNode.h"

#endif // LOLBISON_AST_H_
