#ifndef LOLBISON_AST_FORWARD_DECLARATIONS_H_
#define LOLBISON_AST_FORWARD_DECLARATIONS_H_

class AstNode;
class Program;
class Statement;
class VarDecl;
class VarAssign;
class ArrayDecl;
class ArrayNewIndex;
class ArrayAssign;
class Print;
class IfThen;
class Loop;
class LoopHead;
class IncrementLoopHead;
class DecrementLoopHead;
class LoopCondition;
class LoopWhile;
class LoopUntil;
class Break;
class ExprStatement;
class Expression;
class NumberLiteral;
class StringLiteral;
class BooleanLiteral;
class It;
class Identifier;
class LogicalNot;
class BinaryOp;
class ArrayAccess;
class Join;
class BinarySum;
class BinarySub;
class BinaryMul;
class BinaryDiv;
class BinaryMod;
class BinaryMax;
class BinaryMin;
class BinaryEq;
class BinaryNeq;
class BinaryAnd;
class BinaryOr;
class BinaryXor;

#endif  // LOLBISON_AST_FORWARD_DECLARATIONS_H_
