HAI 1.2
    I HAS A N ITZ 100
    BOTH SAEM N AN -42
    I HAS A string ITZ "CHECK OUT THIS STRING:: I LUV THIS STRING!"
    WON OF DIFFRINT SUM OF DIFF OF 3 AN 5 AN QUOSHUNT OF 9 3 AN BIGGR OF 130 AN 1 AN 5
    NOT N
KTHXBYE
