HAI 1.2
    VISIBLE SUM OF 4 AN -3
    VISIBLE DIFF OF 4 AN -3
    VISIBLE PRODUKT OF 4 AN -3
    VISIBLE QUOSHUNT OF 4 AN -3
    VISIBLE MOD OF 4 AN -3
    VISIBLE BIGGR OF 4 AN -3
    VISIBLE SMALLR OF 4 AN -3

    I HAS A VAR ITZ 100
    VISIBLE SUM OF 0 AN BOTH SAEM 100 VAR
    VISIBLE SUM OF 0 AN DIFFRINT "100" VAR

    VISIBLE SUM OF 0 AN BOTH OF FAIL AN WIN
    VISIBLE SUM OF 0 AN EITHER OF FAIL AN FAIL
    VISIBLE SUM OF 0 AN WON OF WIN AN WIN
    VISIBLE SUM OF 0 AN NOT "who"
KTHXBYE
